use advent_of_code_2022::day7::day7work2;
fn main() {
    if let Err(data) = day7work2() {
        panic!("Something went wrong: {}", data);
    }
}
